app:
  host: "http://localhost"
  port: "8000"
  version: "1.0.0"

database:
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "root"
  name: "defaultdb"

redis:
  host: "127.0.0.1"
  port: "6379"
  password: ""

jwt:
  secret: "jwtsecret123"

signature:
  secret: "signatureSecret!#"
