app:
  host: "http://localhost"
  port: "8000"
  version: "1.0.0"

database:
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "rootpassword"
  name: "klopdb"
# database:
#   host: "172.168.10.40"
#   port: "3306"
#   user: "admin"
#   password: "db3306_TSM@2024"
#   name: "klopdb"

redis:
  host: "127.0.0.1"
  port: "6379"
  password: ""

jwt:
  secret: "appsecret123"

signature:
  secret: "appsecret123!#"
